"""phase 2d market indices

Phase 2D schema (docs/data_sources/phase_2d_indices_design.md): raw daily
index values from the development index files, and the view
``observed_trading_days`` (dates present in stock or index data, with flags).
The view is not seen by autogenerate; it is written by hand below and copied
literally so this migration never depends on later model code.

Revision ID: 6117977fb001
Revises: 55a78b2c9066
Create Date: 2026-09-25 23:53:34.392091

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6117977fb001'
down_revision: Union[str, Sequence[str], None] = '55a78b2c9066'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

OBSERVED_TRADING_DAYS_VIEW = """CREATE VIEW observed_trading_days AS
SELECT d.source_id,
       d.trading_date,
       coalesce(s.stock_rows, 0) AS stock_rows,
       coalesce(i.index_rows, 0) AS index_rows,
       coalesce(s.stock_rows, 0) > 0 AS in_stock_data,
       coalesce(i.index_rows, 0) > 0 AS in_index_data,
       extract(isodow FROM d.trading_date) >= 6 AS is_weekend
FROM (SELECT source_id, trading_date FROM daily_prices
      UNION SELECT source_id, trading_date FROM index_daily_values) d
LEFT JOIN (SELECT source_id, trading_date, count(*) AS stock_rows
           FROM daily_prices GROUP BY 1, 2) s USING (source_id, trading_date)
LEFT JOIN (SELECT source_id, trading_date, count(*) AS index_rows
           FROM index_daily_values GROUP BY 1, 2) i USING (source_id, trading_date)
"""


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('index_daily_values',
    sa.Column('source_id', sa.Text(), nullable=False),
    sa.Column('index_code', sa.Text(), nullable=False),
    sa.Column('trading_date', sa.Date(), nullable=False),
    sa.Column('previous', sa.Numeric(precision=20, scale=4), nullable=False),
    sa.Column('high', sa.Numeric(precision=20, scale=4), nullable=False),
    sa.Column('low', sa.Numeric(precision=20, scale=4), nullable=False),
    sa.Column('close', sa.Numeric(precision=20, scale=4), nullable=False),
    sa.Column('constituents', sa.Integer(), nullable=True),
    sa.Column('volume', sa.BigInteger(), nullable=True),
    sa.Column('value', sa.Numeric(precision=24, scale=4), nullable=True),
    sa.Column('frequency', sa.BigInteger(), nullable=True),
    sa.Column('capitalization', sa.Numeric(precision=24, scale=4), nullable=True),
    sa.Column('quality_flags', postgresql.ARRAY(sa.Text()), server_default=sa.text("'{}'::text[]"), nullable=False),
    sa.Column('file_id', sa.BigInteger(), nullable=False),
    sa.Column('source_line', sa.Integer(), nullable=False),
    sa.Column('ingestion_run_id', sa.Uuid(), nullable=False),
    sa.CheckConstraint("index_code ~ '^[A-Za-z0-9-]+$'", name=op.f('ck_index_daily_values_index_code_format')),
    sa.CheckConstraint("quality_flags <@ ARRAY['unverified_trading_date']::text[] AND array_position(quality_flags, NULL) IS NULL", name=op.f('ck_index_daily_values_quality_flags_vocabulary')),
    sa.CheckConstraint('(constituents IS NULL OR constituents >= 0) AND (volume IS NULL OR volume >= 0) AND (value IS NULL OR value >= 0) AND (frequency IS NULL OR frequency >= 0) AND (capitalization IS NULL OR capitalization >= 0)', name=op.f('ck_index_daily_values_counts_non_negative')),
    sa.CheckConstraint('high >= low AND close >= low AND close <= high', name=op.f('ck_index_daily_values_high_low_close_shape')),
    sa.CheckConstraint('previous > 0 AND high > 0 AND low > 0 AND close > 0', name=op.f('ck_index_daily_values_values_positive')),
    sa.CheckConstraint('source_line >= 1', name=op.f('ck_index_daily_values_source_line_positive')),
    sa.ForeignKeyConstraint(['file_id'], ['source_files.file_id'], name=op.f('fk_index_daily_values_file_id_source_files'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['ingestion_run_id'], ['ingestion_runs.ingestion_run_id'], name=op.f('fk_index_daily_values_ingestion_run_id_ingestion_runs'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['source_id'], ['data_sources.source_id'], name=op.f('fk_index_daily_values_source_id_data_sources'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('source_id', 'index_code', 'trading_date', name=op.f('pk_index_daily_values'))
    )
    op.create_index('ix_index_daily_values_trading_date', 'index_daily_values', ['trading_date'], unique=False)
    # ### end Alembic commands ###
    op.execute(OBSERVED_TRADING_DAYS_VIEW)


def downgrade() -> None:
    """Downgrade schema."""
    op.execute("DROP VIEW observed_trading_days")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_index_daily_values_trading_date', table_name='index_daily_values')
    op.drop_table('index_daily_values')
    # ### end Alembic commands ###
