"""phase 2b market data schema

Initial market-data schema (Phase 2B.2), as approved in
docs/data_sources/phase_2b_schema_design.md: source provenance
(data_sources, source_snapshots, source_files, ingestion_runs), security
identity (securities, security_source_keys), raw daily prices, and
data-quality incidents. All foreign keys are ON DELETE RESTRICT.

Generated with ``alembic revision --autogenerate`` and reviewed by hand.
Autogenerate does not detect later CHECK-constraint changes; any change to a
CHECK vocabulary must be written explicitly in a new migration.

Revision ID: 1c1d7048b74f
Revises:
Create Date: 2026-09-24 19:36:33.551534

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1c1d7048b74f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_sources',
    sa.Column('source_id', sa.Text(), nullable=False),
    sa.Column('source_name', sa.Text(), nullable=False),
    sa.Column('homepage_url', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("source_id ~ '^[a-z0-9][a-z0-9-]*$'", name=op.f('ck_data_sources_source_id_format')),
    sa.PrimaryKeyConstraint('source_id', name=op.f('pk_data_sources'))
    )
    op.create_table('securities',
    sa.Column('security_id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('ticker', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('currency', sa.Text(), server_default=sa.text("'IDR'"), nullable=False),
    sa.Column('identity_kind', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("currency ~ '^[A-Z]{3}$'", name=op.f('ck_securities_currency_format')),
    sa.CheckConstraint("identity_kind IN ('development')", name=op.f('ck_securities_identity_kind_vocabulary')),
    sa.PrimaryKeyConstraint('security_id', name=op.f('pk_securities'))
    )
    op.create_index('ix_securities_ticker', 'securities', ['ticker'], unique=False)
    op.create_table('source_snapshots',
    sa.Column('snapshot_id', sa.Text(), nullable=False),
    sa.Column('source_id', sa.Text(), nullable=False),
    sa.Column('source_revision', sa.Text(), nullable=False),
    sa.Column('content_sha256', sa.Text(), nullable=False),
    sa.Column('archive_sha256', sa.Text(), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=False),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('licence_reference', sa.Text(), nullable=False),
    sa.Column('raw_storage_path', sa.Text(), nullable=False),
    sa.Column('file_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("archive_sha256 IS NULL OR archive_sha256 ~ '^[0-9a-f]{64}$'", name=op.f('ck_source_snapshots_archive_sha256_format')),
    sa.CheckConstraint("content_sha256 ~ '^[0-9a-f]{64}$'", name=op.f('ck_source_snapshots_content_sha256_format')),
    sa.CheckConstraint("snapshot_id = source_id || ':' || source_revision || ':' || left(content_sha256, 16)", name=op.f('ck_source_snapshots_snapshot_id_derived')),
    sa.CheckConstraint('file_count >= 0', name=op.f('ck_source_snapshots_file_count_non_negative')),
    sa.ForeignKeyConstraint(['source_id'], ['data_sources.source_id'], name=op.f('fk_source_snapshots_source_id_data_sources'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('snapshot_id', name=op.f('pk_source_snapshots')),
    sa.UniqueConstraint('source_id', 'source_revision', 'content_sha256', name=op.f('uq_source_snapshots_source_id'))
    )
    op.create_table('ingestion_runs',
    sa.Column('ingestion_run_id', sa.Uuid(), nullable=False),
    sa.Column('snapshot_id', sa.Text(), nullable=False),
    sa.Column('parser_version', sa.Text(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('rows_seen', sa.BigInteger(), server_default=sa.text('0'), nullable=False),
    sa.Column('rows_inserted', sa.BigInteger(), server_default=sa.text('0'), nullable=False),
    sa.Column('rows_unchanged', sa.BigInteger(), server_default=sa.text('0'), nullable=False),
    sa.Column('rows_rejected', sa.BigInteger(), server_default=sa.text('0'), nullable=False),
    sa.Column('rows_conflicted', sa.BigInteger(), server_default=sa.text('0'), nullable=False),
    sa.Column('validation_summary', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.CheckConstraint("(status = 'running') = (completed_at IS NULL)", name=op.f('ck_ingestion_runs_completion_matches_status')),
    sa.CheckConstraint("status IN ('running', 'succeeded', 'failed')", name=op.f('ck_ingestion_runs_status_vocabulary')),
    sa.CheckConstraint('completed_at IS NULL OR completed_at >= started_at', name=op.f('ck_ingestion_runs_completed_after_started')),
    sa.CheckConstraint('rows_seen >= 0 AND rows_inserted >= 0 AND rows_unchanged >= 0 AND rows_rejected >= 0 AND rows_conflicted >= 0', name=op.f('ck_ingestion_runs_row_counts_non_negative')),
    sa.ForeignKeyConstraint(['snapshot_id'], ['source_snapshots.snapshot_id'], name=op.f('fk_ingestion_runs_snapshot_id_source_snapshots'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('ingestion_run_id', name=op.f('pk_ingestion_runs'))
    )
    op.create_index('ix_ingestion_runs_snapshot_id', 'ingestion_runs', ['snapshot_id'], unique=False)
    op.create_table('security_source_keys',
    sa.Column('source_id', sa.Text(), nullable=False),
    sa.Column('source_key', sa.Text(), nullable=False),
    sa.Column('security_id', sa.BigInteger(), nullable=False),
    sa.Column('first_seen_snapshot_id', sa.Text(), nullable=False),
    sa.Column('quality_flags', postgresql.ARRAY(sa.Text()), server_default=sa.text("'{}'::text[]"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("quality_flags <@ ARRAY['source_ticker_column_mismatch']::text[] AND array_position(quality_flags, NULL) IS NULL", name=op.f('ck_security_source_keys_quality_flags_vocabulary')),
    sa.ForeignKeyConstraint(['first_seen_snapshot_id'], ['source_snapshots.snapshot_id'], name=op.f('fk_security_source_keys_first_seen_snapshot_id_source_snapshots'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['security_id'], ['securities.security_id'], name=op.f('fk_security_source_keys_security_id_securities'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['source_id'], ['data_sources.source_id'], name=op.f('fk_security_source_keys_source_id_data_sources'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('source_id', 'source_key', name=op.f('pk_security_source_keys'))
    )
    op.create_index('ix_security_source_keys_security_id', 'security_source_keys', ['security_id'], unique=False)
    op.create_table('source_files',
    sa.Column('file_id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('snapshot_id', sa.Text(), nullable=False),
    sa.Column('relative_path', sa.Text(), nullable=False),
    sa.Column('sha256', sa.Text(), nullable=False),
    sa.Column('row_count', sa.Integer(), nullable=False),
    sa.Column('source_key', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("sha256 ~ '^[0-9a-f]{64}$'", name=op.f('ck_source_files_sha256_format')),
    sa.CheckConstraint('row_count >= 0', name=op.f('ck_source_files_row_count_non_negative')),
    sa.ForeignKeyConstraint(['snapshot_id'], ['source_snapshots.snapshot_id'], name=op.f('fk_source_files_snapshot_id_source_snapshots'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('file_id', name=op.f('pk_source_files')),
    sa.UniqueConstraint('snapshot_id', 'relative_path', name=op.f('uq_source_files_snapshot_id'))
    )
    op.create_table('daily_prices',
    sa.Column('security_id', sa.BigInteger(), nullable=False),
    sa.Column('trading_date', sa.Date(), nullable=False),
    sa.Column('source_id', sa.Text(), nullable=False),
    sa.Column('open', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('high', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('low', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('close', sa.Numeric(precision=20, scale=4), nullable=False),
    sa.Column('reference_price', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('volume', sa.BigInteger(), nullable=True),
    sa.Column('value', sa.Numeric(precision=24, scale=4), nullable=True),
    sa.Column('frequency', sa.BigInteger(), nullable=True),
    sa.Column('trading_status', sa.Text(), nullable=False),
    sa.Column('quality_flags', postgresql.ARRAY(sa.Text()), server_default=sa.text("'{}'::text[]"), nullable=False),
    sa.Column('file_id', sa.BigInteger(), nullable=False),
    sa.Column('source_line', sa.Integer(), nullable=False),
    sa.Column('ingestion_run_id', sa.Uuid(), nullable=False),
    sa.CheckConstraint("quality_flags <@ ARRAY['non_regular_activity_present', 'unverified_trading_date']::text[] AND array_position(quality_flags, NULL) IS NULL", name=op.f('ck_daily_prices_quality_flags_vocabulary')),
    sa.CheckConstraint("trading_status <> 'no_regular_market_trade' OR (volume IS NOT NULL AND volume = 0 AND open IS NULL AND high IS NULL AND low IS NULL)", name=op.f('ck_daily_prices_no_regular_trade_shape')),
    sa.CheckConstraint("trading_status <> 'traded' OR (volume IS NOT NULL AND volume > 0 AND high IS NOT NULL AND low IS NOT NULL AND high >= low AND high >= close AND low <= close AND (open IS NULL OR (open >= low AND open <= high)))", name=op.f('ck_daily_prices_traded_shape')),
    sa.CheckConstraint("trading_status IN ('traded', 'no_regular_market_trade', 'unknown')", name=op.f('ck_daily_prices_trading_status_vocabulary')),
    sa.CheckConstraint('close > 0', name=op.f('ck_daily_prices_close_positive')),
    sa.CheckConstraint('frequency IS NULL OR frequency >= 0', name=op.f('ck_daily_prices_frequency_non_negative')),
    sa.CheckConstraint('high IS NULL OR high > 0', name=op.f('ck_daily_prices_high_positive')),
    sa.CheckConstraint('low IS NULL OR low > 0', name=op.f('ck_daily_prices_low_positive')),
    sa.CheckConstraint('open IS NULL OR open > 0', name=op.f('ck_daily_prices_open_positive')),
    sa.CheckConstraint('reference_price IS NULL OR reference_price > 0', name=op.f('ck_daily_prices_reference_price_positive')),
    sa.CheckConstraint('source_line >= 1', name=op.f('ck_daily_prices_source_line_positive')),
    sa.CheckConstraint('value IS NULL OR value >= 0', name=op.f('ck_daily_prices_value_non_negative')),
    sa.CheckConstraint('volume IS NULL OR volume >= 0', name=op.f('ck_daily_prices_volume_non_negative')),
    sa.ForeignKeyConstraint(['file_id'], ['source_files.file_id'], name=op.f('fk_daily_prices_file_id_source_files'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['ingestion_run_id'], ['ingestion_runs.ingestion_run_id'], name=op.f('fk_daily_prices_ingestion_run_id_ingestion_runs'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['security_id'], ['securities.security_id'], name=op.f('fk_daily_prices_security_id_securities'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['source_id'], ['data_sources.source_id'], name=op.f('fk_daily_prices_source_id_data_sources'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('security_id', 'trading_date', 'source_id', name=op.f('pk_daily_prices'))
    )
    op.create_index('ix_daily_prices_trading_date', 'daily_prices', ['trading_date'], unique=False)
    op.create_table('data_quality_incidents',
    sa.Column('incident_id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('ingestion_run_id', sa.Uuid(), nullable=False),
    sa.Column('incident_type', sa.Text(), nullable=False),
    sa.Column('severity', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), server_default=sa.text("'open'"), nullable=False),
    sa.Column('source_id', sa.Text(), nullable=True),
    sa.Column('security_id', sa.BigInteger(), nullable=True),
    sa.Column('trading_date', sa.Date(), nullable=True),
    sa.Column('file_id', sa.BigInteger(), nullable=True),
    sa.Column('source_line', sa.Integer(), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("incident_type IN ('conflicting_observation', 'conflicting_duplicate_in_snapshot', 'hard_invalid_record', 'source_ticker_column_mismatch', 'snapshot_content_mismatch')", name=op.f('ck_data_quality_incidents_incident_type_vocabulary')),
    sa.CheckConstraint("severity IN ('error', 'warning', 'info')", name=op.f('ck_data_quality_incidents_severity_vocabulary')),
    sa.CheckConstraint("status IN ('open', 'resolved', 'accepted')", name=op.f('ck_data_quality_incidents_status_vocabulary')),
    sa.CheckConstraint('source_line IS NULL OR source_line >= 1', name=op.f('ck_data_quality_incidents_source_line_positive')),
    sa.ForeignKeyConstraint(['file_id'], ['source_files.file_id'], name=op.f('fk_data_quality_incidents_file_id_source_files'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['ingestion_run_id'], ['ingestion_runs.ingestion_run_id'], name=op.f('fk_data_quality_incidents_ingestion_run_id_ingestion_runs'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['security_id'], ['securities.security_id'], name=op.f('fk_data_quality_incidents_security_id_securities'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['source_id'], ['data_sources.source_id'], name=op.f('fk_data_quality_incidents_source_id_data_sources'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('incident_id', name=op.f('pk_data_quality_incidents'))
    )
    op.create_index('ix_data_quality_incidents_ingestion_run_id', 'data_quality_incidents', ['ingestion_run_id'], unique=False)
    op.create_index('ix_data_quality_incidents_security_id_trading_date', 'data_quality_incidents', ['security_id', 'trading_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_data_quality_incidents_security_id_trading_date', table_name='data_quality_incidents')
    op.drop_index('ix_data_quality_incidents_ingestion_run_id', table_name='data_quality_incidents')
    op.drop_table('data_quality_incidents')
    op.drop_index('ix_daily_prices_trading_date', table_name='daily_prices')
    op.drop_table('daily_prices')
    op.drop_table('source_files')
    op.drop_index('ix_security_source_keys_security_id', table_name='security_source_keys')
    op.drop_table('security_source_keys')
    op.drop_index('ix_ingestion_runs_snapshot_id', table_name='ingestion_runs')
    op.drop_table('ingestion_runs')
    op.drop_table('source_snapshots')
    op.drop_index('ix_securities_ticker', table_name='securities')
    op.drop_table('securities')
    op.drop_table('data_sources')
    # ### end Alembic commands ###
