"""phase 2c corporate actions and adjustment factors

Phase 2C-2 schema, as approved in
docs/data_sources/phase_2c_corporate_actions_design.md: raw corporate-action
events and cash dividends (with provenance), adjustment builds, derived
price-adjustment factors, and derived reference-price anomaly dates.
``daily_prices`` is not changed. All foreign keys are ON DELETE RESTRICT.

It also adds the incident type ``malformed_optional_field`` (an optional
source field that cannot be parsed is stored as NULL, and the raw value is
recorded in an incident). Autogenerate cannot detect that CHECK change, so
it is written by hand at the end of ``upgrade``/start of ``downgrade``.

Generated with ``alembic revision --autogenerate`` and reviewed by hand.

Revision ID: 55a78b2c9066
Revises: 1c1d7048b74f
Create Date: 2026-09-25 16:03:39.956104

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '55a78b2c9066'
down_revision: Union[str, Sequence[str], None] = '1c1d7048b74f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

INCIDENT_TYPES_2B = "'conflicting_observation', 'conflicting_duplicate_in_snapshot', 'hard_invalid_record', 'source_ticker_column_mismatch', 'snapshot_content_mismatch'"
INCIDENT_TYPES_2C = "'conflicting_observation', 'conflicting_duplicate_in_snapshot', 'hard_invalid_record', 'source_ticker_column_mismatch', 'snapshot_content_mismatch', 'malformed_optional_field'"


def _set_incident_types(values: str) -> None:
    """Replace the incident_type vocabulary CHECK (not autogenerated)."""
    op.drop_constraint(
        op.f('ck_data_quality_incidents_incident_type_vocabulary'),
        'data_quality_incidents',
        type_='check',
    )
    op.create_check_constraint(
        op.f('ck_data_quality_incidents_incident_type_vocabulary'),
        'data_quality_incidents',
        f"incident_type IN ({values})",
    )


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('adjustment_builds',
    sa.Column('build_id', sa.Uuid(), nullable=False),
    sa.Column('price_source_id', sa.Text(), nullable=False),
    sa.Column('method_version', sa.Text(), nullable=False),
    sa.Column('parameters', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('inputs', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('summary', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('built_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['price_source_id'], ['data_sources.source_id'], name=op.f('fk_adjustment_builds_price_source_id_data_sources'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('build_id', name=op.f('pk_adjustment_builds'))
    )
    op.create_table('reference_price_anomaly_dates',
    sa.Column('price_source_id', sa.Text(), nullable=False),
    sa.Column('method_version', sa.Text(), nullable=False),
    sa.Column('trading_date', sa.Date(), nullable=False),
    sa.Column('build_id', sa.Uuid(), nullable=False),
    sa.Column('mismatched_securities', sa.Integer(), nullable=False),
    sa.Column('compared_securities', sa.Integer(), nullable=False),
    sa.Column('shifted_row_matches', sa.Integer(), nullable=False),
    sa.CheckConstraint('mismatched_securities >= 0 AND compared_securities >= mismatched_securities', name=op.f('ck_reference_price_anomaly_dates_counts_consistent')),
    sa.ForeignKeyConstraint(['build_id'], ['adjustment_builds.build_id'], name=op.f('fk_reference_price_anomaly_dates_build_id_adjustment_builds'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['price_source_id'], ['data_sources.source_id'], name=op.f('fk_reference_price_anomaly_dates_price_source_id_data_sources'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('price_source_id', 'method_version', 'trading_date', name=op.f('pk_reference_price_anomaly_dates'))
    )
    op.create_table('cash_dividends',
    sa.Column('dividend_id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('source_id', sa.Text(), nullable=False),
    sa.Column('source_ticker', sa.Text(), nullable=False),
    sa.Column('ex_date', sa.Date(), nullable=False),
    sa.Column('security_id', sa.BigInteger(), nullable=True),
    sa.Column('security_match', sa.Text(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=30, scale=16), nullable=False),
    sa.Column('amount_basis', sa.Text(), nullable=False),
    sa.Column('currency', sa.Text(), server_default=sa.text("'IDR'"), nullable=False),
    sa.Column('dividend_type', sa.Text(), nullable=False),
    sa.Column('fiscal_year', sa.Integer(), nullable=True),
    sa.Column('payment_date', sa.Date(), nullable=True),
    sa.Column('file_id', sa.BigInteger(), nullable=False),
    sa.Column('record_ref', sa.Text(), nullable=False),
    sa.Column('ingestion_run_id', sa.Uuid(), nullable=False),
    sa.CheckConstraint("(security_match = 'unmatched') = (security_id IS NULL)", name=op.f('ck_cash_dividends_security_match_consistent')),
    sa.CheckConstraint("amount_basis IN ('gross', 'net', 'unstated')", name=op.f('ck_cash_dividends_amount_basis_vocabulary')),
    sa.CheckConstraint("security_match IN ('ticker_text_match', 'unmatched')", name=op.f('ck_cash_dividends_security_match_vocabulary')),
    sa.CheckConstraint('amount > 0', name=op.f('ck_cash_dividends_amount_positive')),
    sa.ForeignKeyConstraint(['file_id'], ['source_files.file_id'], name=op.f('fk_cash_dividends_file_id_source_files'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['ingestion_run_id'], ['ingestion_runs.ingestion_run_id'], name=op.f('fk_cash_dividends_ingestion_run_id_ingestion_runs'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['security_id'], ['securities.security_id'], name=op.f('fk_cash_dividends_security_id_securities'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['source_id'], ['data_sources.source_id'], name=op.f('fk_cash_dividends_source_id_data_sources'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('dividend_id', name=op.f('pk_cash_dividends')),
    sa.UniqueConstraint('source_id', 'source_ticker', 'ex_date', name=op.f('uq_cash_dividends_source_id'))
    )
    op.create_index('ix_cash_dividends_security_id_ex_date', 'cash_dividends', ['security_id', 'ex_date'], unique=False)
    op.create_table('corporate_action_events',
    sa.Column('event_id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('source_id', sa.Text(), nullable=False),
    sa.Column('source_record_id', sa.Text(), nullable=False),
    sa.Column('source_category', sa.Text(), nullable=False),
    sa.Column('source_action_label', sa.Text(), nullable=False),
    sa.Column('source_ticker', sa.Text(), nullable=False),
    sa.Column('security_id', sa.BigInteger(), nullable=True),
    sa.Column('security_match', sa.Text(), nullable=False),
    sa.Column('registration_date', sa.Date(), nullable=False),
    sa.Column('shares_involved', sa.Numeric(precision=24, scale=4), nullable=True),
    sa.Column('shares_after', sa.Numeric(precision=24, scale=4), nullable=True),
    sa.Column('file_id', sa.BigInteger(), nullable=False),
    sa.Column('record_ref', sa.Text(), nullable=False),
    sa.Column('ingestion_run_id', sa.Uuid(), nullable=False),
    sa.CheckConstraint("(security_match = 'unmatched') = (security_id IS NULL)", name=op.f('ck_corporate_action_events_security_match_consistent')),
    sa.CheckConstraint("security_match IN ('ticker_text_match', 'unmatched')", name=op.f('ck_corporate_action_events_security_match_vocabulary')),
    sa.CheckConstraint('shares_after IS NULL OR shares_after >= 0', name=op.f('ck_corporate_action_events_shares_after_non_negative')),
    sa.CheckConstraint('shares_involved IS NULL OR shares_involved >= 0', name=op.f('ck_corporate_action_events_shares_involved_non_negative')),
    sa.ForeignKeyConstraint(['file_id'], ['source_files.file_id'], name=op.f('fk_corporate_action_events_file_id_source_files'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['ingestion_run_id'], ['ingestion_runs.ingestion_run_id'], name=op.f('fk_corporate_action_events_ingestion_run_id_ingestion_runs'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['security_id'], ['securities.security_id'], name=op.f('fk_corporate_action_events_security_id_securities'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['source_id'], ['data_sources.source_id'], name=op.f('fk_corporate_action_events_source_id_data_sources'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('event_id', name=op.f('pk_corporate_action_events')),
    sa.UniqueConstraint('source_id', 'source_record_id', name=op.f('uq_corporate_action_events_source_id'))
    )
    op.create_index('ix_corporate_action_events_security_id_date', 'corporate_action_events', ['security_id', 'registration_date'], unique=False)
    op.create_table('price_adjustment_factors',
    sa.Column('price_source_id', sa.Text(), nullable=False),
    sa.Column('method_version', sa.Text(), nullable=False),
    sa.Column('security_id', sa.BigInteger(), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('factor_kind', sa.Text(), nullable=False),
    sa.Column('build_id', sa.Uuid(), nullable=False),
    sa.Column('factor', sa.Numeric(), nullable=False),
    sa.Column('classification', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('reference_price', sa.Numeric(precision=20, scale=4), nullable=False),
    sa.Column('close', sa.Numeric(precision=20, scale=4), nullable=False),
    sa.Column('prev_trading_date', sa.Date(), nullable=True),
    sa.Column('prev_close', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('dividend_amount', sa.Numeric(precision=30, scale=16), nullable=True),
    sa.Column('source_ex_date', sa.Date(), nullable=True),
    sa.Column('corporate_action_event_id', sa.BigInteger(), nullable=True),
    sa.Column('file_id', sa.BigInteger(), nullable=False),
    sa.Column('source_line', sa.Integer(), nullable=False),
    sa.Column('prev_file_id', sa.BigInteger(), nullable=True),
    sa.Column('prev_source_line', sa.Integer(), nullable=True),
    sa.CheckConstraint("(factor_kind = 'cash_dividend') = (classification = 'cash_dividend')", name=op.f('ck_price_adjustment_factors_classification_matches_kind')),
    sa.CheckConstraint("(factor_kind = 'cash_dividend') = (dividend_amount IS NOT NULL)", name=op.f('ck_price_adjustment_factors_dividend_amount_iff_dividend')),
    sa.CheckConstraint("classification IN ('split', 'reverse_split', 'rights', 'bonus', 'stock_dividend', 'unclassified', 'cash_dividend')", name=op.f('ck_price_adjustment_factors_classification_vocabulary')),
    sa.CheckConstraint("factor_kind <> 'price' OR (prev_close IS NOT NULL AND prev_trading_date IS NOT NULL)", name=op.f('ck_price_adjustment_factors_price_factor_has_previous_row')),
    sa.CheckConstraint("factor_kind IN ('price', 'cash_dividend')", name=op.f('ck_price_adjustment_factors_factor_kind_vocabulary')),
    sa.CheckConstraint("status IN ('applied', 'excluded_market_wide_anomaly')", name=op.f('ck_price_adjustment_factors_status_vocabulary')),
    sa.CheckConstraint('factor > 0', name=op.f('ck_price_adjustment_factors_factor_positive')),
    sa.CheckConstraint('source_line >= 1', name=op.f('ck_price_adjustment_factors_source_line_positive')),
    sa.ForeignKeyConstraint(['build_id'], ['adjustment_builds.build_id'], name=op.f('fk_price_adjustment_factors_build_id_adjustment_builds'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['corporate_action_event_id'], ['corporate_action_events.event_id'], name=op.f('fk_price_adjustment_factors_corporate_action_event_id_corporate_action_events'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['file_id'], ['source_files.file_id'], name=op.f('fk_price_adjustment_factors_file_id_source_files'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['prev_file_id'], ['source_files.file_id'], name=op.f('fk_price_adjustment_factors_prev_file_id_source_files'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['price_source_id'], ['data_sources.source_id'], name=op.f('fk_price_adjustment_factors_price_source_id_data_sources'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['security_id'], ['securities.security_id'], name=op.f('fk_price_adjustment_factors_security_id_securities'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('price_source_id', 'method_version', 'security_id', 'effective_date', 'factor_kind', name=op.f('pk_price_adjustment_factors'))
    )
    # ### end Alembic commands ###
    _set_incident_types(INCIDENT_TYPES_2C)


def downgrade() -> None:
    """Downgrade schema."""
    _set_incident_types(INCIDENT_TYPES_2B)
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('price_adjustment_factors')
    op.drop_index('ix_corporate_action_events_security_id_date', table_name='corporate_action_events')
    op.drop_table('corporate_action_events')
    op.drop_index('ix_cash_dividends_security_id_ex_date', table_name='cash_dividends')
    op.drop_table('cash_dividends')
    op.drop_table('reference_price_anomaly_dates')
    op.drop_table('adjustment_builds')
    # ### end Alembic commands ###
